### ISSUE TITLE
SIGABRT or SIGSEGV when i want to run a command

### ISSUE THREAD

**Issue by kC0pter** [streamduck-org/streamduck#9]
**Description**
OS: Kubuntu 22.04 LTS
I configure a button with a renderer and a command parameter.
Renderer has a picture bound to it without a text.
Command is in simple mode for both errors.
The systemd daemon logs shows:
- `Execution of command returned: signal: 6 (SIGABRT) (core dumped)` for the command `/usr/bin/konsole` 
- `Execution of command returned: signal: 11 (SIGSEGV) (core dumped)` for the command `spotify %U`

**Steps to Reproduce**
Create a button, add the renderer, add the `Run command` action and set the Command to either one of the previously explained commands. (Make sure to have spotify and konsole as the terminal emu installed.

**Expected behavior**
To either have konsole or spotify pop up as a window to use.

**Screenshots**
Screenshot of the button configs:
![Screenshot_20230323_144646](https://user-images.githubusercontent.com/42284664/227223748-28f165f1-e5c4-4d4c-b365-f9bc33761e5f.png)
![Screenshot_20230323_145012](https://user-images.githubusercontent.com/42284664/227224407-0e3b8d09-ac58-4001-a26b-b0ac2dd617f6.png)

Screenshot of the output in the systemd logs:
![Screenshot_20230323_144846](https://user-images.githubusercontent.com/42284664/227224127-34aaf544-5600-4347-941f-d9c89f1e1c49.png)

**Comment by TheJebForge** [comment]
Not entirely sure why it's breaking for you, the code is executing the command directly however, so you could try using something like `sh -c <your command here>` in case the system doesn't support having things run without a shell first..

**Comment by kC0pter** [comment]
I tried it with simple command `sh -c /usr/bin/konsole`and with advanced split as `sh`, `-c` and `/usr/bin/konsole`.
Still get this log in the daemon log and `exit status: 134` is SIGABRT: 
![Screenshot_20230324_095213](https://user-images.githubusercontent.com/42284664/227471435-35f6fcf8-0496-4868-870a-f87db1047e30.png)

**Comment by kC0pter** [comment]
Upon further inspection, the first issue it may be is due to the daemon using the `Command::output()` instead of the `spawn()` function in the [run_command action](https://github.com/streamduck-org/streamduck/blob/bfd49d4d000e221ba89839a0d34140f4fb8c5f61/streamduck-actions/src/run_command.rs#L149). First one waits for completion and the second one spawns the process as a child process and returns a handle to the process which is non-blocking compared to the `output()` call.

Second issue is, that according to the [Process::Command::output() Docs](https://doc.rust-lang.org/std/process/struct.Command.html#method.output) stdout and stderr are captured and stdin is not available. This may lead to the specified behaviour. The `spawn()` function inherits the stdout, stderr and stdin from the parent, which may not work with the daemon since it is running headless.

I tried running an isolated example of the `Command::output()` with my command and it worked without an issue.
Example code as follows:
```rust
use std::process::Command;

fn main() {
    println!("Hello, world!");

    let output = Command::new("konsole").output();

    println!("Test debug point.");
}
```
Even replacing the `output()`with `spawn()` worked.

**Comment by TheJebForge** [comment]
Project shifted to dotnet basically throwing away all the old code, so no longer applicable
